import { connectToDatabase } from "@/lib/db/mongoose";
import Framework from "@/models/Framework";
import "dotenv/config";
import path from "path";
import dotenv from "dotenv";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const FRAMEWORKS = [
  {
    name: "React", slug: "react", category: "frontend", color: "#61dafb", language: "JavaScript",
    description: "A JavaScript library for building user interfaces with component-based architecture.",
    longDescription: "React is a declarative, efficient, and flexible JavaScript library for building user interfaces. It lets you compose complex UIs from small and isolated pieces of code called 'components'. Created by Facebook, React has become the most popular frontend library, with a massive ecosystem and community.",
    level: ["junior", "mid", "senior"], tags: ["components", "jsx", "virtual-dom", "hooks"],
    stars: 220000, weeklyDownloads: 25000000, releaseYear: 2013,
    performance: 85, learningCurve: 60, ecosystem: 98, jobMarket: 98,
    pros: ["Huge ecosystem", "Strong community", "Component reusability", "React Native for mobile", "Meta backing"],
    cons: ["JSX learning curve", "Rapid changes", "Not opinionated (more choices needed)", "Bundle size"],
    useCases: ["Single Page Applications", "Progressive Web Apps", "Mobile apps with React Native", "Complex UIs"],
    officialDocs: "https://react.dev", githubUrl: "https://github.com/facebook/react",
    setupSteps: [
      { step: 1, explanation: "Create a new React app using Vite", command: "npm create vite@latest my-app -- --template react-ts" },
      { step: 2, explanation: "Install dependencies", command: "cd my-app && npm install" },
      { step: 3, explanation: "Start the development server", command: "npm run dev" },
    ],
    codeSnippets: [
      { title: "Hello World", language: "jsx", code: "function App() {\n  return <h1>Hello, React!</h1>;\n}\nexport default App;" },
      { title: "useState Hook", language: "jsx", code: "import { useState } from 'react';\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(c => c + 1)}>Count: {count}</button>;\n}" },
    ],
  },
  {
    name: "Vue", slug: "vue", category: "frontend", color: "#42b883", language: "JavaScript",
    description: "The progressive JavaScript framework for building modern web interfaces.",
    longDescription: "Vue.js is an open-source model–view–viewmodel front end JavaScript framework for building user interfaces and single-page applications. Vue's design is centered around progressive adoption — the core library focuses on the view layer only, and is easy to pick up and integrate with other libraries or existing projects.",
    level: ["junior", "mid"], tags: ["reactive", "components", "sfc", "composition-api"],
    stars: 208000, weeklyDownloads: 5000000, releaseYear: 2014,
    performance: 88, learningCurve: 45, ecosystem: 85, jobMarket: 82,
    pros: ["Gentle learning curve", "Excellent documentation", "Single File Components", "Flexible and scalable"],
    cons: ["Smaller job market than React", "Mostly Asia/Europe market", "Fewer third-party resources"],
    useCases: ["SPAs", "UI components", "PWAs", "Enterprise applications"],
    officialDocs: "https://vuejs.org", githubUrl: "https://github.com/vuejs/core",
    setupSteps: [
      { step: 1, explanation: "Create a new Vue 3 app", command: "npm create vue@latest" },
      { step: 2, explanation: "Install dependencies", command: "npm install" },
      { step: 3, explanation: "Start dev server", command: "npm run dev" },
    ],
    codeSnippets: [{ title: "Hello World", language: "html", code: "<template>\n  <h1>{{ message }}</h1>\n</template>\n<script setup>\nconst message = 'Hello Vue 3!';\n</script>" }],
  },
  {
    name: "Next.js", slug: "nextjs", category: "fullstack", color: "#ffffff", language: "JavaScript",
    description: "The React framework for production — hybrid SSR and SSG with file-based routing.",
    longDescription: "Next.js is an open-source web development framework created by Vercel enabling React-based web applications with server-side rendering and generating static websites. It has become the go-to fullstack framework for React developers, offering built-in routing, API routes, image optimization, and edge deployment.",
    level: ["mid", "senior"], tags: ["ssr", "ssg", "api-routes", "react", "vercel"],
    stars: 125000, weeklyDownloads: 8000000, releaseYear: 2016,
    performance: 95, learningCurve: 65, ecosystem: 94, jobMarket: 95,
    pros: ["Excellent DX", "Built-in optimization", "Hybrid rendering", "Edge functions", "Vercel integration"],
    cons: ["Vercel lock-in concerns", "App Router complexity", "Cold start times"],
    useCases: ["E-commerce", "Marketing sites", "SaaS dashboards", "Blogs"],
    officialDocs: "https://nextjs.org", githubUrl: "https://github.com/vercel/next.js",
    setupSteps: [
      { step: 1, explanation: "Create a Next.js app", command: "npx create-next-app@latest my-app --yes" },
      { step: 2, explanation: "Start development server", command: "cd my-app && npm run dev" },
    ],
    codeSnippets: [{ title: "Page Component", language: "tsx", code: "export default function Page() {\n  return <main><h1>Hello Next.js!</h1></main>;\n}" }],
  },
  {
    name: "Angular", slug: "angular", category: "frontend", color: "#dd0031", language: "TypeScript",
    description: "Platform for building mobile and desktop web applications using TypeScript.",
    longDescription: "Angular is a TypeScript-based free and open-source web application framework led by the Angular Team at Google. It is a complete rewrite from the same team that built AngularJS. Angular uses a component-based architecture with built-in dependency injection, TypeScript, and a powerful CLI.",
    level: ["mid", "senior"], tags: ["typescript", "di", "rxjs", "cli"],
    stars: 95000, weeklyDownloads: 3500000, releaseYear: 2016,
    performance: 80, learningCurve: 75, ecosystem: 90, jobMarket: 88,
    pros: ["Complete framework", "TypeScript by default", "Strong conventions", "Enterprise-ready", "Google backing"],
    cons: ["Steep learning curve", "Verbose code", "Heavy bundle", "RxJS complexity"],
    useCases: ["Enterprise apps", "Complex dashboards", "Large teams"],
    officialDocs: "https://angular.io", githubUrl: "https://github.com/angular/angular",
    setupSteps: [
      { step: 1, explanation: "Install Angular CLI", command: "npm install -g @angular/cli" },
      { step: 2, explanation: "Create new app", command: "ng new my-app" },
      { step: 3, explanation: "Serve app", command: "cd my-app && ng serve" },
    ],
    codeSnippets: [{ title: "Component", language: "typescript", code: "import { Component } from '@angular/core';\n@Component({ selector: 'app-root', template: '<h1>Hello Angular!</h1>' })\nexport class AppComponent {}" }],
  },
  {
    name: "Svelte", slug: "svelte", category: "frontend", color: "#ff3e00", language: "JavaScript",
    description: "Cybernetically enhanced web apps — a compiler that generates vanilla JS with no virtual DOM.",
    longDescription: "Svelte is a radical new approach to building user interfaces. Whereas traditional frameworks like React and Vue do the bulk of their work in the browser, Svelte shifts that work into a compile step that happens when you build your app, resulting in blazing fast runtime performance.",
    level: ["junior", "mid"], tags: ["compiler", "reactive", "lightweight", "no-virtual-dom"],
    stars: 79000, weeklyDownloads: 1000000, releaseYear: 2016,
    performance: 97, learningCurve: 40, ecosystem: 65, jobMarket: 55,
    pros: ["Fastest performance", "Minimal boilerplate", "Easy syntax", "Small bundle size"],
    cons: ["Smaller ecosystem", "Fewer jobs", "Less community resources"],
    useCases: ["Interactive UIs", "Performance-critical apps", "Personal projects"],
    officialDocs: "https://svelte.dev", githubUrl: "https://github.com/sveltejs/svelte",
    setupSteps: [
      { step: 1, explanation: "Create Svelte app", command: "npm create svelte@latest my-app" },
      { step: 2, explanation: "Install and run", command: "cd my-app && npm install && npm run dev" },
    ],
    codeSnippets: [{ title: "Counter", language: "html", code: "<script>\n  let count = 0;\n</script>\n<button on:click={() => count++}>Count: {count}</button>" }],
  },
  {
    name: "SvelteKit", slug: "sveltekit", category: "fullstack", color: "#ff3e00", language: "JavaScript",
    description: "The fastest way to build Svelte apps — a fullstack framework with file-based routing.",
    longDescription: "SvelteKit is a framework for rapidly developing robust, performant web applications using Svelte. It provides file-based routing, SSR, SSG, API routes, and adapters for any deployment target.",
    level: ["mid"], tags: ["svelte", "ssr", "routing", "adapters"],
    stars: 20000, weeklyDownloads: 400000, releaseYear: 2021,
    performance: 98, learningCurve: 45, ecosystem: 60, jobMarket: 45,
    pros: ["Top performance", "Great DX", "Flexible adapters", "Type-safe"],
    cons: ["Small ecosystem", "Niche community"],
    useCases: ["Blogs", "Marketing sites", "Fullstack apps"],
    officialDocs: "https://kit.svelte.dev", githubUrl: "https://github.com/sveltejs/kit",
    setupSteps: [{ step: 1, explanation: "Create SvelteKit app", command: "npm create svelte@latest my-app" }],
    codeSnippets: [{ title: "Page", language: "html", code: "<h1>Hello SvelteKit!</h1>" }],
  },
  {
    name: "Nuxt", slug: "nuxt", category: "fullstack", color: "#00dc82", language: "JavaScript",
    description: "The intuitive Vue framework with SSR, SSG, and auto-imports.",
    longDescription: "Nuxt is a free and open-source framework with an intuitive and extendable way to create type-safe, performant and production-grade full-stack web applications and websites with Vue.js.",
    level: ["mid"], tags: ["vue", "ssr", "ssg", "auto-imports"],
    stars: 55000, weeklyDownloads: 1200000, releaseYear: 2016,
    performance: 90, learningCurve: 55, ecosystem: 78, jobMarket: 70,
    pros: ["Vue ecosystem", "Auto-imports", "Zero config", "Nitro server"],
    cons: ["Slower than Next.js", "Smaller community"],
    useCases: ["Vue apps requiring SSR", "E-commerce", "Blogs"],
    officialDocs: "https://nuxt.com", githubUrl: "https://github.com/nuxt/nuxt",
    setupSteps: [{ step: 1, explanation: "Create Nuxt app", command: "npx nuxi@latest init my-app" }],
    codeSnippets: [{ title: "Page", language: "html", code: "<template>\n  <NuxtPage />\n</template>" }],
  },
  {
    name: "Astro", slug: "astro", category: "fullstack", color: "#ff5d01", language: "JavaScript",
    description: "The all-in-one web framework designed for speed — ships zero JavaScript by default.",
    longDescription: "Astro is an all-in-one web framework for building fast, content-focused websites. Astro pulls from the best of the modern web while offering a first-class developer experience. You can use any JavaScript UI component library (React, Preact, Svelte, Vue, etc.) within Astro.",
    level: ["mid", "senior"], tags: ["islands", "static", "performance", "content"],
    stars: 45000, weeklyDownloads: 800000, releaseYear: 2021,
    performance: 99, learningCurve: 50, ecosystem: 65, jobMarket: 55,
    pros: ["Zero JS by default", "Framework-agnostic", "Incredible performance", "Island architecture"],
    cons: ["Not for dynamic apps", "Smaller job market"],
    useCases: ["Blogs", "Documentation", "Marketing sites", "Content-heavy sites"],
    officialDocs: "https://astro.build", githubUrl: "https://github.com/withastro/astro",
    setupSteps: [{ step: 1, explanation: "Create Astro app", command: "npm create astro@latest" }],
    codeSnippets: [{ title: "Page", language: "html", code: "---\nconst title = 'Hello Astro!';\n---\n<html><body><h1>{title}</h1></body></html>" }],
  },
  {
    name: "Remix", slug: "remix", category: "fullstack", color: "#e8f2ff", language: "JavaScript",
    description: "Full stack web framework focused on web fundamentals and modern UX.",
    longDescription: "Remix is a full stack web framework that lets you focus on the user interface and work back through web standards to deliver a fast, slick, and resilient user experience.",
    level: ["mid", "senior"], tags: ["react", "loaders", "actions", "web-standards"],
    stars: 30000, weeklyDownloads: 600000, releaseYear: 2021,
    performance: 92, learningCurve: 60, ecosystem: 70, jobMarket: 65,
    pros: ["Web standards focus", "Nested routing", "Excellent error handling", "Progressive enhancement"],
    cons: ["Smaller community than Next.js", "Fewer templates"],
    useCases: ["SaaS apps", "E-commerce", "Enterprise web apps"],
    officialDocs: "https://remix.run", githubUrl: "https://github.com/remix-run/remix",
    setupSteps: [{ step: 1, explanation: "Create Remix app", command: "npx create-remix@latest" }],
    codeSnippets: [{ title: "Loader", language: "tsx", code: "export async function loader() {\n  return { hello: 'world' };\n}" }],
  },
  {
    name: "Express", slug: "express", category: "backend", color: "#68a063", language: "JavaScript",
    description: "Fast, unopinionated, minimalist web framework for Node.js.",
    longDescription: "Express.js is a back end web application framework for building RESTful APIs with Node.js. It is designed for building web applications and APIs and is the most popular Node.js framework with over 32 million weekly downloads.",
    level: ["junior", "mid"], tags: ["nodejs", "rest", "middleware", "api"],
    stars: 64000, weeklyDownloads: 32000000, releaseYear: 2010,
    performance: 82, learningCurve: 35, ecosystem: 95, jobMarket: 90,
    pros: ["Minimal and flexible", "Huge ecosystem", "Easy to learn", "Most popular Node.js framework"],
    cons: ["No opinions — lots of decisions", "Callback hell potential", "Not typed by default"],
    useCases: ["REST APIs", "Backend services", "Microservices"],
    officialDocs: "https://expressjs.com", githubUrl: "https://github.com/expressjs/express",
    setupSteps: [
      { step: 1, explanation: "Create project and install Express", command: "mkdir my-api && cd my-api && npm init -y && npm install express" },
      { step: 2, explanation: "Create server file and start", command: "node index.js" },
    ],
    codeSnippets: [{ title: "Basic Server", language: "javascript", code: "const express = require('express');\nconst app = express();\napp.get('/', (req, res) => res.json({ hello: 'world' }));\napp.listen(3000);" }],
  },
  {
    name: "Fastify", slug: "fastify", category: "backend", color: "#00b0d7", language: "JavaScript",
    description: "Fast and low overhead web framework for Node.js — 2x faster than Express.",
    longDescription: "Fastify is a web framework highly focused on providing the best developer experience with the least overhead and a powerful plugin architecture. It is inspired by Hapi and Express and as far as we know, it is one of the fastest web frameworks in town.",
    level: ["mid", "senior"], tags: ["nodejs", "performance", "schema", "typescript"],
    stars: 32000, weeklyDownloads: 3000000, releaseYear: 2016,
    performance: 98, learningCurve: 50, ecosystem: 75, jobMarket: 65,
    pros: ["Blazing fast", "Schema validation", "Plugin system", "TypeScript support"],
    cons: ["Smaller community than Express", "Less middleware"],
    useCases: ["High-performance APIs", "Microservices"],
    officialDocs: "https://fastify.io", githubUrl: "https://github.com/fastify/fastify",
    setupSteps: [{ step: 1, explanation: "Install Fastify", command: "npm install fastify" }],
    codeSnippets: [{ title: "Basic", language: "javascript", code: "const fastify = require('fastify')();\nfastify.get('/', async () => ({ hello: 'world' }));\nfastify.listen({ port: 3000 });" }],
  },
  {
    name: "NestJS", slug: "nestjs", category: "backend", color: "#e0234e", language: "TypeScript",
    description: "A progressive Node.js framework for building efficient and scalable server-side applications.",
    longDescription: "Nest (NestJS) is a framework for building efficient, scalable Node.js server-side applications. It uses progressive JavaScript, is built with and fully supports TypeScript, and combines elements of OOP, FP, and FRP.",
    level: ["mid", "senior"], tags: ["typescript", "decorators", "di", "microservices"],
    stars: 67000, weeklyDownloads: 2200000, releaseYear: 2017,
    performance: 88, learningCurve: 70, ecosystem: 82, jobMarket: 82,
    pros: ["Angular-like structure", "Built-in DI", "TypeScript first", "Great for enterprise"],
    cons: ["Steep learning curve", "Heavy boilerplate", "Over-engineered for small apps"],
    useCases: ["Enterprise APIs", "Microservices", "GraphQL", "gRPC"],
    officialDocs: "https://nestjs.com", githubUrl: "https://github.com/nestjs/nest",
    setupSteps: [
      { step: 1, explanation: "Install NestJS CLI", command: "npm i -g @nestjs/cli" },
      { step: 2, explanation: "Create project", command: "nest new my-app" },
    ],
    codeSnippets: [{ title: "Controller", language: "typescript", code: "@Controller('cats')\nexport class CatsController {\n  @Get()\n  findAll(): string { return 'This returns all cats'; }\n}" }],
  },
  {
    name: "Django", slug: "django", category: "backend", color: "#2ba977", language: "Python",
    description: "The web framework for perfectionists with deadlines — batteries included.",
    longDescription: "Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design. Built by experienced developers, it takes care of much of the hassle of web development, so you can focus on writing your app without needing to reinvent the wheel.",
    level: ["junior", "mid", "senior"], tags: ["python", "orm", "admin", "full-stack"],
    stars: 79000, weeklyDownloads: 1500000, releaseYear: 2005,
    performance: 75, learningCurve: 50, ecosystem: 88, jobMarket: 85,
    pros: ["Batteries included", "Great ORM", "Admin panel", "Security built-in"],
    cons: ["Monolithic", "ORM can be slow", "REST APIs need extra libraries"],
    useCases: ["Web apps", "REST APIs with DRF", "Content management", "Data science backends"],
    officialDocs: "https://djangoproject.com", githubUrl: "https://github.com/django/django",
    setupSteps: [
      { step: 1, explanation: "Install Django", command: "pip install django" },
      { step: 2, explanation: "Create project", command: "django-admin startproject myproject" },
      { step: 3, explanation: "Run server", command: "python manage.py runserver" },
    ],
    codeSnippets: [{ title: "View", language: "python", code: "from django.http import JsonResponse\ndef hello(request):\n    return JsonResponse({'hello': 'Django'})" }],
  },
  {
    name: "FastAPI", slug: "fastapi", category: "backend", color: "#009688", language: "Python",
    description: "Modern, fast web framework for building APIs with Python based on standard type hints.",
    longDescription: "FastAPI is a modern, fast (high-performance), web framework for building APIs with Python based on standard Python type hints. The key features are: fast (one of the fastest Python frameworks), fast to code, fewer bugs, intuitive, easy, short, and production-ready.",
    level: ["junior", "mid", "senior"], tags: ["python", "async", "openapi", "pydantic"],
    stars: 75000, weeklyDownloads: 2000000, releaseYear: 2018,
    performance: 98, learningCurve: 40, ecosystem: 80, jobMarket: 78,
    pros: ["Auto OpenAPI docs", "Type hints", "Async support", "Pydantic validation", "Fast"],
    cons: ["Newer ecosystem", "Async complexity", "Less ORM options"],
    useCases: ["REST APIs", "ML model serving", "Data APIs", "Microservices"],
    officialDocs: "https://fastapi.tiangolo.com", githubUrl: "https://github.com/tiangolo/fastapi",
    setupSteps: [
      { step: 1, explanation: "Install FastAPI and uvicorn", command: "pip install fastapi uvicorn" },
      { step: 2, explanation: "Run the server", command: "uvicorn main:app --reload" },
    ],
    codeSnippets: [{ title: "Basic API", language: "python", code: "from fastapi import FastAPI\napp = FastAPI()\n@app.get('/')\nasync def root():\n    return {'message': 'Hello FastAPI'}" }],
  },
  {
    name: "Laravel", slug: "laravel", category: "backend", color: "#ff2d20", language: "PHP",
    description: "The PHP Framework for Web Artisans — elegant syntax with powerful features.",
    longDescription: "Laravel is a web application framework with expressive, elegant syntax. It provides a clean and simple API for the most common web development tasks, including routing, Eloquent ORM, blade templating, queues, broadcasting, and more.",
    level: ["junior", "mid", "senior"], tags: ["php", "orm", "artisan", "eloquent"],
    stars: 78000, weeklyDownloads: 500000, releaseYear: 2011,
    performance: 70, learningCurve: 45, ecosystem: 90, jobMarket: 80,
    pros: ["Elegant syntax", "Great ORM", "Strong conventions", "Ecosystem (Vapor, Forge)"],
    cons: ["PHP perception", "Performance limitations", "High memory usage"],
    useCases: ["Web apps", "E-commerce", "REST APIs", "Enterprise apps"],
    officialDocs: "https://laravel.com", githubUrl: "https://github.com/laravel/laravel",
    setupSteps: [{ step: 1, explanation: "Create Laravel project", command: "composer create-project laravel/laravel my-app" }],
    codeSnippets: [{ title: "Route", language: "php", code: "Route::get('/hello', function () {\n    return response()->json(['hello' => 'Laravel']);\n});" }],
  },
  {
    name: "Spring Boot", slug: "spring-boot", category: "backend", color: "#6db33f", language: "Java",
    description: "Convention-over-configuration Java framework for production-grade Spring applications.",
    longDescription: "Spring Boot makes it easy to create stand-alone, production-grade Spring based Applications that you can just run. It takes an opinionated view of the Spring platform and third-party libraries so you can get started with minimum fuss.",
    level: ["mid", "senior"], tags: ["java", "enterprise", "microservices", "spring"],
    stars: 74000, weeklyDownloads: 1000000, releaseYear: 2014,
    performance: 85, learningCurve: 70, ecosystem: 95, jobMarket: 92,
    pros: ["Enterprise proven", "Auto-configuration", "Huge ecosystem", "Strong types"],
    cons: ["Verbose", "Long startup time", "Complex configuration"],
    useCases: ["Enterprise APIs", "Banking systems", "Microservices"],
    officialDocs: "https://spring.io/projects/spring-boot", githubUrl: "https://github.com/spring-projects/spring-boot",
    setupSteps: [{ step: 1, explanation: "Create project via Spring Initializr", command: "curl https://start.spring.io/starter.zip -o demo.zip" }],
    codeSnippets: [{ title: "Controller", language: "java", code: "@RestController\npublic class HelloController {\n    @GetMapping(\"/hello\")\n    public String hello() { return \"Hello Spring Boot!\"; }\n}" }],
  },
  {
    name: "Gin", slug: "gin", category: "backend", color: "#00acd7", language: "Go",
    description: "The fastest full-featured web framework for Go — up to 40x faster than Martini.",
    longDescription: "Gin is a web framework written in Go. It features a Martini-like API with much better performance -- up to 40 times faster. If you need smashing performance, get yourself some Gin.",
    level: ["mid", "senior"], tags: ["go", "performance", "rest", "fast"],
    stars: 77000, weeklyDownloads: 400000, releaseYear: 2014,
    performance: 99, learningCurve: 55, ecosystem: 72, jobMarket: 70,
    pros: ["Blazing performance", "Simple API", "Great for microservices", "Low memory"],
    cons: ["Go learning curve", "Smaller ecosystem", "Less ORM support"],
    useCases: ["High-performance APIs", "Microservices", "System tools"],
    officialDocs: "https://gin-gonic.com", githubUrl: "https://github.com/gin-gonic/gin",
    setupSteps: [
      { step: 1, explanation: "Initialize Go module", command: "go mod init myapp" },
      { step: 2, explanation: "Install Gin", command: "go get -u github.com/gin-gonic/gin" },
    ],
    codeSnippets: [{ title: "Basic", language: "go", code: 'package main\nimport "github.com/gin-gonic/gin"\nfunc main() {\n    r := gin.Default()\n    r.GET("/hello", func(c *gin.Context) {\n        c.JSON(200, gin.H{"hello": "gin"})\n    })\n    r.Run()\n}' }],
  },
  {
    name: "React Native", slug: "react-native", category: "mobile", color: "#61dafb", language: "JavaScript",
    description: "Build native mobile apps for Android and iOS using React.",
    longDescription: "React Native combines the best parts of native development with React, a best-in-class JavaScript library for building user interfaces. Use a little—or a lot. You can use React Native today in your existing Android and iOS projects or you can create a whole new app from scratch.",
    level: ["mid", "senior"], tags: ["mobile", "native", "cross-platform", "react"],
    stars: 118000, weeklyDownloads: 1800000, releaseYear: 2015,
    performance: 80, learningCurve: 65, ecosystem: 85, jobMarket: 88,
    pros: ["Code sharing with web React", "Large community", "Native performance", "Hot reload"],
    cons: ["Bridge overhead", "Native module complexity", "Platform differences"],
    useCases: ["Cross-platform mobile apps", "React developers going mobile"],
    officialDocs: "https://reactnative.dev", githubUrl: "https://github.com/facebook/react-native",
    setupSteps: [{ step: 1, explanation: "Create app with Expo", command: "npx create-expo-app@latest my-app" }],
    codeSnippets: [{ title: "Basic", language: "jsx", code: "import { Text, View } from 'react-native';\nexport default function App() {\n  return <View><Text>Hello React Native!</Text></View>;\n}" }],
  },
  {
    name: "Flutter", slug: "flutter", category: "mobile", color: "#54c5f8", language: "Dart",
    description: "Google's UI toolkit for building natively compiled apps from a single codebase.",
    longDescription: "Flutter is an open source framework by Google for building beautiful, natively compiled, multi-platform applications from a single codebase. Flutter code compiles to ARM or Intel machine code as well as JavaScript, for fast performance on any device.",
    level: ["junior", "mid", "senior"], tags: ["dart", "cross-platform", "widgets", "google"],
    stars: 165000, weeklyDownloads: 800000, releaseYear: 2017,
    performance: 95, learningCurve: 60, ecosystem: 80, jobMarket: 82,
    pros: ["Great performance", "Single codebase for 6 platforms", "Rich widget library", "Hot reload"],
    cons: ["Dart language", "Large app size", "Web support improving"],
    useCases: ["Mobile apps", "Desktop apps", "Web apps"],
    officialDocs: "https://flutter.dev", githubUrl: "https://github.com/flutter/flutter",
    setupSteps: [{ step: 1, explanation: "Create Flutter app", command: "flutter create my_app" }],
    codeSnippets: [{ title: "Widget", language: "dart", code: "import 'package:flutter/material.dart';\nvoid main() => runApp(const Center(child: Text('Hello Flutter!')));" }],
  },
  {
    name: "Tailwind CSS", slug: "tailwind", category: "css", color: "#38bdf8", language: "CSS",
    description: "A utility-first CSS framework for rapidly building custom user interfaces.",
    longDescription: "Tailwind CSS is a utility-first CSS framework packed with classes like flex, pt-4, text-center and rotate-90 that can be composed to build any design, directly in your markup. It never includes unused CSS, resulting in tiny production bundles.",
    level: ["junior", "mid", "senior"], tags: ["utility-first", "responsive", "customizable", "jit"],
    stars: 83000, weeklyDownloads: 10000000, releaseYear: 2017,
    performance: 90, learningCurve: 40, ecosystem: 92, jobMarket: 90,
    pros: ["Rapid development", "No naming conventions needed", "Responsive utilities", "JIT compilation"],
    cons: ["Long class strings", "Learning all utilities", "Not pure CSS"],
    useCases: ["Any web project", "Design systems", "Rapid prototyping"],
    officialDocs: "https://tailwindcss.com", githubUrl: "https://github.com/tailwindlabs/tailwindcss",
    setupSteps: [{ step: 1, explanation: "Install Tailwind CSS", command: "npm install tailwindcss @tailwindcss/vite" }],
    codeSnippets: [{ title: "Button", language: "html", code: '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">\n  Click me\n</button>' }],
  },
  {
    name: "Jest", slug: "jest", category: "testing", color: "#c21325", language: "JavaScript",
    description: "Delightful JavaScript Testing Framework with a focus on simplicity.",
    longDescription: "Jest is a JavaScript testing framework maintained by Meta. It is designed to ensure the correctness of any JavaScript codebase, with zero configuration for most projects. It includes a test runner, assertion library, and mocking framework all in one.",
    level: ["junior", "mid", "senior"], tags: ["testing", "mocking", "coverage", "snapshots"],
    stars: 44000, weeklyDownloads: 24000000, releaseYear: 2014,
    performance: 85, learningCurve: 40, ecosystem: 95, jobMarket: 90,
    pros: ["Zero config", "Great DX", "Snapshot testing", "Built-in coverage"],
    cons: ["Can be slow for large suites", "ESM support issues historically"],
    useCases: ["Unit testing", "Integration testing", "React component testing"],
    officialDocs: "https://jestjs.io", githubUrl: "https://github.com/jestjs/jest",
    setupSteps: [{ step: 1, explanation: "Install Jest", command: "npm install --save-dev jest" }],
    codeSnippets: [{ title: "Test", language: "javascript", code: "test('adds 1 + 2 to equal 3', () => {\n  expect(1 + 2).toBe(3);\n});" }],
  },
];

async function seed() {
  try {
    await connectToDatabase();
    console.log("Connected to MongoDB");

    await Framework.deleteMany({});
    console.log("Cleared existing frameworks");

    const result = await Framework.insertMany(FRAMEWORKS);
    console.log(`✅ Seeded ${result.length} frameworks`);
    process.exit(0);
  } catch (err) {
    console.error("Seed failed:", err);
    process.exit(1);
  }
}

seed();
